name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Clone
        run: git clone https://github.com/davidfauthoux/nope-boardgame.git && pwd
      - name: Clone 2
        run: https://${{ secrets.REPO }}@github.com/davidfauthoux/nop.git
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pwd & yarn
    
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run ESLint
      # You may pin to the exact commit or the version.
      # uses: stefanoeb/eslint-action@0b532bcd98dbed80a59071fa8986fcf1b1715be4
      uses: stefanoeb/eslint-action@1.0.2
      with:
        # Blob of files to lint
        files: .
 

