# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone
      - run:  git clone https://github.com/davidfauthoux/nop.git nop && 
              cd nope && 
              git clone git@github.com:davidfauthoux/nope-book.git book &&
              git clone git@github.com:davidfauthoux/nope-tilt.git tilt &&
              git clone git@github.com:davidfauthoux/nope-welcome.git welcome &&
              git clone git@github.com:davidfauthoux/nope-boardgame.git boardgame &&
              cd boardgame
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: yarn
    
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2

    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        # Blob of files to lint
        files: .
    
 
 

