# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: yarn
    
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2

    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        # Blob of files to lint
        files: .
    
 
 

