# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
      with :
        ref: ${{ github.head_ref }}
        fetch_depth: 0

    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        # Blob of files to lint
        files: .
        
    - name: Prettier Action
      # You may pin to the exact commit or the version.
      # uses: creyD/prettier_action@cb975d8aad896ac567efb5dffc07653fb42abdb7
      uses: creyD/prettier_action@v3.3
      with:
        # Commit message, will be ignored if used with same_commit
        only_changed: True
 
 

