name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone

      # You may pin to the exact commit or the version.
      # uses: GuillaumeFalourd/clone-github-repo-action@d667f8c39e6ac1dd5309ad51b0020657c7a1a296
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
        # Repository Owner
          owner:  davidfauthoux 
        # Repository name
          repository: nope-boardgame
        # PAT with repository scope (https://github.com/settings/tokens)
          #access-token: # optional  
      - name: Clone 2

      # You may pin to the exact commit or the version.
      # uses: GuillaumeFalourd/clone-github-repo-action@d667f8c39e6ac1dd5309ad51b0020657c7a1a296
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
        # Repository Owner
          owner:  davidfauthoux 
        # Repository name
          repository: nop
        # PAT with repository scope (https://github.com/settings/tokens)
          access-token:  ${{ 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 }}
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
    
  build:
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        # Blob of files to lint
        files: .
    
 

